# main tasks file
---
- name: Include gate.yml
  include: gate.yml

# - name: Include Percona install
#   include: "{{ ansible_distribution | lower}}_perc.yml"

# - name: Setup Percona for Morpheus
#   include: morpheus_db_setup.yml

- name: Include Rabbit Install
  include: "{{ ansible_distribution | lower}}_rabbit.yml"
  when: "'rabbit' in group_names"

- name: Setup Rabbitmq for morpheus
  include: morpheus_rabbit_setup.yml
