- name: Install Morpheus
  hosts: all
  become: True
  pre_tasks:
    - name: include global_vars.yml
      include_vars: ./vars/global_vars.yml

    - name: Get packages
      package_facts:
      
  tasks:
    - name: PLAY | Help message
      debug:
        msg:
          - This is the help message
          - Tags 
          - AIO - install the morpheus All in One appliance
          - 3node - install the morpheus 3 node method
          - full - install morpheus with a full HA with X number of nodes
          - setup - complete the morpheus_initial_setup
      tags:
        - help
          
    - name: Install AIO Morpheus
      include_role: 
        name: install_aio_morpheus
        apply:
          tags:
            - AIO
            - install
            - debug
      tags: AIO

    - name: Install 3Node HA Morpheus
      include_role:
        name: install_3node_morpheus
        apply:
          tags:
          - 3node
      tags: 
        - 3node

    - name: Install Full HA Morpheus
      include_role: 
        name: install_fullha_morpheus
        apply:
          tags: 
            - full
            - install
            - debug
      tags: 
        - full

    - name: Morpheus Initial Setup
      include_role:
        name: morpheus_initial_setup
        apply:
          tags:
            - setup
            - debug
      tags: 
        - setup

      