- name: Install Morpheus
  hosts: all
  become: True
  pre_tasks:
    - name: include global_vars.yml
      include_vars: ./vars/global_vars.yml

    - name: Get packages
      package_facts:

    - name: Install 3Node HA Morpheus
      include_role:
        name: install_3node_morpheus

      