- name: Install Moprheus Full HA
  hosts: all
  become: True
  pre_tasks:
    - name: include global_vars.yml
      include_vars: ./vars/global_vars.yml

    - name: Get packages
      package_facts:
      
  tasks:
    - name: Install full HA environment
      include_role: 
        name: lin_install_aio_morpheus