- name: Install Morpheus
  hosts: all
  become: true
  vars_prompt:
    - name: m_username
      prompt: Please enter Morpheus Username to login with
      private: no
    - name: m_password
      prompt: Please enter Morpheus Password
      private: yes  

  pre_tasks:
    - name: PLAY | include global_vars.yml
      include_vars: ./vars/global_vars.yml

    - name: PLAY | Get packages
      package_facts:

  tasks:
    - name: PLAY | Morpheus initial setup
      include_role:
        name: morpheus_initial_setup
        apply:
          tags:
            - initial
      tags: 
        - initial
        - debug

    - name: PLAY | Morpheus tenant setup
      include_role:
        name: morpheus_tenant_create
        apply:
          tags:
            - tenant
      tags:
        - tenant
        - debug
