- name: morphues_elastic_setup | Add elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
    backup: True

- name: morphues_elastic_setup | Start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: True
  