- name: INITIAL SETUP | Set password fact
  set_fact:
    set_m_password: "{{ m_password }}"

- name: INITIAL SETUP | print generated password
  debug:
    msg: 
      - "test"
      - "{{ set_m_password }}"
  

- name: INITIAL SETUP | Call API To do init tenant setup
  uri:
    url: "{{ m_base_url }}/api/setup/init"
    method: POST
    body_format: json
    body:
      applianceName: "{{ m_base_url }}"
      applianceUrl: "{{ m_base_url }}"
      accountName: "Master Tenant"
      username: "admin"
      password: "{{ set_m_password }}"
      email: "admin@morpheusdata.com"
      firstName: "Admin"
    follow_redirects: true
    validate_certs: false
  when: ping_chk.json.setupNeeded
