---
- name: MAIN | Include gate.
  include: gate.yml
  tags: always

- name: MAIN | Block for RHEL variant install.
  block:
    - name: MAIN | Download the RPM
      get_url:
        url: https://downloads.morpheusdata.com/files/morpheus-appliance-{{ m_release }}.el{{ ansible_distribution_major_version }}.x86_64.rpm 
        dest: /tmp/morpheus-appliance-{{ m_release }}.el{{ ansible_distribution_major_version }}.x86_64.rpm

    - name: MAIN | Install Morpheus RPM.
      yum:
        name: /tmp/morpheus-appliance-{{ m_release }}.el{{ ansible_distribution_major_version }}.x86_64.rpm
        state: present
  when: > 
    ansible_distribution | lower == 'centos'
    or ansible_distribution | lower == 'redhat'
  tags: install

- name: MAIN | Block for Debian variant install.
  block:
    - name: MAIN | Download the package.
      get_url:
        url: https://downloads.morpheusdata.com/files/morpheus-appliance_{{ m_release }}_amd64.deb 
        dest: /tmp/morpheus-appliance_{{ m_release }}_amd64.deb

    - name: MAIN | Install the package
      apt:
        deb: /tmp/morpheus-appliance_{{ m_release }}_amd64.deb
  when: > 
    ansible_distribution | lower == 'ubuntu'
  tags: install

- name: MAIN | RUN morpheus-ctl reconfigure. ( This takes a while be patient )
  command: 'morpheus-ctl reconfigure'
  register: morph_config_out
  tags: install

- name: MAIN | Debug msg out for reconfigure. 
  debug:
    msg: 
      - "Morpheus reconfigure output"
      - "{{ morph_config_out.stdout_lines }}"
  tags: debug

