# File for gate testing before running a role on server
- name: General | Get services
  service_facts:

- name: Gate General | setfacts
  set_fact:
    firewall_state: "{{ ansible_facts.services['firewalld.service'].state }}"
    firewall_status: "{{ ansible_facts.services['firewalld.service'].status }}"
