- name: Rabbit | Run Rabbit in detached mode
  command: 'rabbitmq-server -detached'

- name: Rabbit | Fetch erlang cookie from remote
  fetch:
    src: "/var/lib/rabbitmq/{{ item }}" 
    dest: "/tmp/{{ hostvars['node1'].node }}_{{ item }}"
  with_items:
    - .erlang.cookie

- name: Rabbit | Copy erlang cookie to remote
  copy:
    src: "/tmp/{{ hostvars['node1'].node }}_{{ item }}/node1/var/lib/rabbitmq/{{ item }}"
    dest: "/var/lib/rabbitmq/{{ item }}"
    mode: 0400
    owner: rabbitmq
    group: rabbitmq
    backup: True
  with_items:
    - .erlang.cookie